name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: clockpilot_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Setup test environment
      run: |
        cp .env.example .env.test
        sed -i 's/localhost:5432/localhost:5432/g' .env.test
        sed -i 's/clockpilot_dev/clockpilot_test/g' .env.test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/clockpilot_test

    - name: Run database migrations
      run: npm run db:push
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/clockpilot_test

    - name: Build application
      run: npm run build

    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASE_URL: http://localhost:5000
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/clockpilot_test
        JWT_SECRET: test-jwt-secret-key-for-ci-environment-only
        SESSION_SECRET: test-session-secret-for-ci

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30

  e2e-tests-mobile:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: clockpilot_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Setup test environment
      run: |
        cp .env.example .env.test
        sed -i 's/localhost:5432/localhost:5432/g' .env.test
        sed -i 's/clockpilot_dev/clockpilot_test/g' .env.test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/clockpilot_test

    - name: Run database migrations
      run: npm run db:push
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/clockpilot_test

    - name: Build application
      run: npm run build

    - name: Run Mobile Tests
      run: npx playwright test --project="Mobile Chrome" --project="Mobile Safari"
      env:
        BASE_URL: http://localhost:5000
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/clockpilot_test
        JWT_SECRET: test-jwt-secret-key-for-ci-environment-only
        SESSION_SECRET: test-session-secret-for-ci

    - name: Upload Mobile Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mobile-test-results
        path: test-results/
        retention-days: 30

  performance-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: e2e-tests
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install chromium

    - name: Run Performance Tests
      run: npx playwright test --project=chromium --grep="@performance"
      env:
        BASE_URL: http://localhost:5000
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/clockpilot_test

    - name: Upload Performance Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results
        path: test-results/
        retention-days: 30